<template>
<div>
    <h2>分类</h2>
    <div class="wrapper">
        <ul>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            <li>擦擦擦擦</li>
            
        </ul>
    </div>
    
</div>
</template>

<script>
import BScroll from 'better-scroll'
export default {
    mounted(){
        const bscroll = new BScroll('.wrapper',{
            // probeType:3,
            click:false,
            pullUpLoad:true
        })
        // bscroll.on('scroll',pos => {
        //     console.log(pos)
        // })
        bscroll.on('pullingUp',() => {
            console.log('擦擦擦擦')
            bscroll.finishPullUp()
        })
    },
    methods:{
        aaa(){
            console.log('----')
            
        }
    }
}
</script>

<style>
.wrapper {
    height: 300px;
    overflow:hidden;
    /* overflow-y:scroll; */
}
</style>